DROP TABLE LOGS;

CREATE TABLE LOGS(
    LOGID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 800000, INCREMENT BY 1),
    USERID INTEGER NOT NULL,
    PRODUCTID INTEGER,
    DETAILS VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    LOGDATE TIMESTAMP NOT NULL,
    PRIMARY KEY(LOGID)
);

SELECT * FROM LOGS;



