DROP TABLE IOTUSER.LOGS;

CREATE TABLE IOTUSER.LOGS(
    LOGID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 800000, INCREMENT BY 1),
    USERID INTEGER NOT NULL,
    PRODUCTID INTEGER,
    DETAILS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    LOGDATE DATE NOT NULL,
    PRIMARY KEY(LOGID)
);

SELECT * FROM IOTUSER.LOGS;



