DROP TABLE IOTUSER.ORDERDB;

CREATE TABLE IOTUSER.ORDERDB(
    ORDERID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 300000, INCREMENT BY 1),
    USERID INTEGER NOT NULL,
    STATUS VARCHAR(20),
    PRIMARY KEY(ORDERID)
);

INSERT INTO IOTUSER.ORDERDB (USERID,STATUS)
VALUES 
    (100000, 'AWAITING PAYMENT'),
    (100001, 'AWAITING PACKAGING'),
    (100002, 'AWAITING DELIVERY'),
    (100003, 'DELIVERED'),
    (100004, 'REVOKED');

SELECT * FROM IOTUSER.ORDERDB;