CREATE TABLE "ACCOUNT"(
    USER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1,  INCREMENT BY 1),
    NAME VARCHAR(30) NOT NULL,
    DOB DATE NOT NULL,
    PHONE VARCHAR(12) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(50) NOT NULL
);

INSERT INTO "ACCOUNT" ("NAME", "DOB", "PHONE", "ADDRESS", "EMAIL", "PASSWORD_HASH") VALUES (
    'Jack', '2000-01-01', '+61400000000', '12 Smith Street', 'rando@uts.com','345#$%#$%$#%3453GSTGR'
);