CREATE TABLE "INVOICE"(
    INVOICE_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1,  INCREMENT BY 1),
    AMOUNT DOUBLE NOT NULL,
    PAID DOUBLE NOT NULL,
    CREATED_TS DATE NOT NULL,
    PAID_TS DATE,
    STATUS VARCHAR(20) NOT NULL
);

INSERT INTO "INVOICE" ("AMOUNT", "PAID", "CREATED_TS", "PAID_TS", "STATUS") VALUES (
    10,10,'2022-04-19','2022-04-19','PAID'
);