CREATE TABLE "ORDER_LINE_ITEM"(
    ORDER_LINE_ITEM_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1,  INCREMENT BY 1),
    ORDER_ID INTEGER UNIQUE,
    SUPPLY_ID INTEGER NOT NULL,
    COST DOUBLE NOT NULL,
    QUANTITY INTEGER NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    STORAGE_LOCATION VARCHAR(100) NOT NULL,
    TAX DOUBLE NOT NULL,
    FOREIGN KEY(ORDER_ID) REFERENCES "ORDER"(ORDER_ID),
    FOREIGN KEY(SUPPLY_ID) REFERENCES SUPPLY(SUPPLY_ID),
    PRIMARY KEY(ORDER_LINE_ITEM_ID, ORDER_ID, SUPPLY_ID)
);

INSERT INTO "ORDER_LINE_ITEM" ("ORDER_ID", "SUPPLY_ID", "COST", "QUANTITY", "NAME", "STORAGE_LOCATION", "TAX") VALUES (
    1, 1, 100, 23, 'Timber 3x3', 'Sydney', 23
);