CREATE TABLE "ORDER"(
    ORDER_ID INTEGER UNIQUE GENERATED ALWAYS AS IDENTITY (START WITH 1,  INCREMENT BY 1),
    CUSTOMER_ID INTEGER NOT NULL,
    STAFF_ID INTEGER NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY(STAFF_ID) REFERENCES STAFF(STAFF_ID),
    PRIMARY KEY(ORDER_ID, CUSTOMER_ID, STAFF_ID)
);

INSERT INTO "ORDER" ("CUSTOMER_ID", "STAFF_ID", "STATUS") VALUES (
    1, 1, 'PREPARING'
);