CREATE TABLE "SHIPMENT"(
    SHIPMENT_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1,  INCREMENT BY 1),
    TRACKING_NUMBER INTEGER NOT NULL,
    CARRIER VARCHAR(20) NOT NULL,
    CURRENT_LOCATION VARCHAR(100) NOT NULL,
    STATUS VARCHAR(20) NOT NULL
);

INSERT INTO "SHIPMENT" ("TRACKING_NUMBER", "CARRIER", "CURRENT_LOCATION", "STATUS") VALUES (
    234589345, 'AUPOST', 'Chullora', 'IN TRANSIT'
);