CREATE TABLE "SUPPLIER"(
    SUPPLIER_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1,  INCREMENT BY 1),
    NAME VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

INSERT INTO "SUPPLIER" ("NAME", "ADDRESS", "EMAIL") VALUES (
    'John','15 Hitchcock Lane', 'john@uts.com'
);