CREATE TABLE "SUPPLY"(
    SUPPLY_ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1,  INCREMENT BY 1),
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    PRODUCT_PRICE DOUBLE NOT NULL,
    DISCOUNT INTEGER NOT NULL,
    PRODUCT_ADDED_DATE DATE NOT NULL,
    PRODUCT_WEIGHT INTEGER NOT NULL,
    PRODUCT_EXPIRY_DATE DATE NOT NULL,
    PRODUCT_HEIGHT INTEGER NOT NULL,
    PRODuCT_WIDTH INTEGER NOT NULL,
    PRODUCT_LENGTH INTEGER NOT NULL,
    PRODUCT_LOCATION VARCHAR(50) NOT NULL,
    PRODUCT_CATEGORY VARCHAR(20) NOT NULL
);

INSERT INTO "SUPPLY" ("PRODUCT_NAME", "PRODUCT_PRICE", "DISCOUNT", "PRODUCT_ADDED_DATE","PRODUCT_WEIGHT","PRODUCT_EXPIRY_DATE",
                      "PRODUCT_HEIGHT","PRODUCT_WIDTH","PRODUCT_LENGTH","PRODUCT_LOCATION", "PRODUCT_CATEGORY") VALUES (
    'Timber 4x4', 50, 0, '2010-06-07',103,'2050-02-05',345,234,534,'Sydney','Wood'
);